---
title: "voter_turnout"
author: "Morgan Llufrio"
date: "10/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r data_read}
# view current working directory with command 'getwd()' or 'pwd'
dat <- read_csv('data/2018-10-09/voter_turnout.csv', col_names = TRUE)
dat <- 
  dat %>% select(-X1)  #removing un-named 'X1' column
head(dat)
```

```{r data_mani}
#%>%#left_join(dat,president_names)

president_years <- seq(1980, 2012, 4)
as.integer(dat_years <- c(1980, 1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998, 2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014))
dat_names <- c("Jimmy Carter", "Ronald Reagan", "Ronald Reagan", "Ronald Reagan", "Ronald Reagan", "George H. W. Bush", "George H. W. Bush", "William J. Clinton", "William J. Clinton", "William J. Clinton", "William J. Clinton", "George W. Bush", "George W. Bush", "George W. Bush", "George W. Bush", "Barack Obama", "Barack Obama", "Barack Obama")
president_names <- data.frame(dat_names, dat_years)

voters <- dat %>% 
  filter(alphanumeric_state_code != 0) %>% 
  group_by(year) %>% 
  summarise(voters = sum(votes, na.rm = TRUE), pop = sum(eligible_voters, na.rm = TRUE), non_voters = (pop - voters)) %>% 
  mutate(election_type = if_else(year %in% president_years, "president year", "midterm year")) %>% 
  left_join(president_names, by = c('year' = 'dat_years')) 
 voters
```


```{r data_viz}

g <- ggplot(voters, aes(x = year)) + 
  geom_point(aes(y = voters, shape = election_type, color = dat_names, size = 4.5)) + #geom_smooth will use the rolling mean 
  #geom_point(aes(y = pop)) +
  geom_line(aes(y = pop, color = dat_names)) +
  #ge
  #geom_line(aes(y = non_voters, color = election_type)) +
  scale_x_continuous(breaks = president_years) + #seq(1980,2014,4)) +
  geom_line(aes(y = voters))
g
```











